### ISSUE TITLE
TestCases.xls->TestSuite or/and TestName even if containing special characters like '&' not giving error

### ISSUE THREAD

**Issue by krajat2000** [MrBricodage/TestLink--ImportExcelMacro#11]
TestCases.xls->TestSuite or/and TestName columns in Testcases excel - even if contains special characters like '&' are not giving error.

Problem in code: NbErreursFormat  in module ExportTestCaseXML not getting updated post update from checkNameParam in Libraries.

Debugged Reason: Public NbErreursFormat is declared Public but inside sub ExportTestCaseXML again declared as local Dim NbErreursFormat As Integer.
Same issue exists for all variables below:
Public errorStr As String
Public warningStr As String
Public NbErreursFormat
Public NbWarningFormat

Solution Proposed: Remove local declaration of below in Sub ExportTestCaseXML

Public errorStr As String
Public warningStr As String
Public NbErreursFormat
Public NbWarningFormat

**Comment by MrBricodage** [comment]
Thank you for your feedback. 
The bug has been fixed.
FYI, same problem was present in file 01.

Regards

**Comment by krajat2000** [comment]
Great.  Thanks. Will check.
Br,
Rajat.
