### ISSUE TITLE
use it in international version of office

### ISSUE THREAD

**Issue by mawoyou** [MrBricodage/TestLink--ImportExcelMacro#14]
I love this app and I have been using it with no problem  but I shared it with some of my chinese friends and it did not work.
they have a simplified chinese windows 7 with simplified chinese office.

**Comment by MrBricodage** [comment]
> it did not work
can you please provide more information about the problem? Or provide a sample of the data used? Hard to help without it.

If some characters are garbled (that is the only issue reported in a international environment), see issue 
#7

**Comment by MrBricodage** [comment]
Hello mawoyou, 

Can you please provide feedback about this issue? 

Regards 

Mr.B

**Comment by MrBricodage** [comment]
No more feedback. 
Issue closed
