### ISSUE TITLE
Missing keyword field

### ISSUE THREAD

**Issue by lnun13** [MrBricodage/TestLink--ImportExcelMacro#27]
Hello.
I cannot found "keyword" column on 02-ImportTestCasesIntoTestLink.xls file although it is specified in 02-ImportTestCasesIntoTestLinkHowTo.pdf. I searched on the last two versions.
Is there something I did not see?
Thanks for your help.
Regards

**Comment by MrBricodage** [comment]
Did you display hidden columns in Excel?

**Comment by lnun13** [comment]
Yes, that was the first thing I tried.
By the way, I am using Excel of office pro 2016.

Thanks for your help.

**Comment by MrBricodage** [comment]
What is presented on column J?

**Comment by lnun13** [comment]
Sorry. I saw I used a previous release (20150817) instead of the latest one I just downloaded.
The column is there. (in previous one, it was custom field)
Thanks.
