### ISSUE TITLE
Import XML into ImportExcelMacro tool Failed. Error "Running Error '9' index bound"

### ISSUE THREAD

**Issue by kellykbl** [MrBricodage/TestLink--ImportExcelMacro#5]
Hello MrBricodage,
I am using your ImportExcelMacro tools more than 1 year. But When I updated testlink from 1.9.12 to 1.9.13. I can't import XML to ExcelMacro template.

My reproduce steps as below.

These steps in Testlink:
1. I have a test project "A", it has many test suites, about 800 test cases;
2. Choose the highest test suite of "A" test project;
3. Click Action button on right panel;
4. Click Export button, all the fields are default value;
5. Export successully;

These steps in MrBricodage's ImportExcelMacro tool:
1. Open "02-ImportTestCasesIntoTestLink.xls" template;
2. Enable macro;
3. Click "Import TestCases From Testlink" button;
4. Prompt "The content in this Excel sheet will be deleted. Are you sure?
5. Click OK button;
6. Choose the above exported XML file from Testlink;
7. It will import some test cases and prompt an error, "Running Error '9' index bound";
8. Click finish button;
9. Result is that it only imported first test suit successfully, and other test suits failed.

PS: When I used testlink version 1.9.12, I also use same ExcelMacro template and same operation steps, all of test project test suites can be imported into MrBricodage's ImportExcelMacro template.
I tried your 20150331 version, also has this issue.

Please help me.
Thanks advance.

**Comment by MrBricodage** [comment]
Hi
Please provide me your file with 800+ items exported from testlink. l need it to reproduce the issue.

**Comment by kellykbl** [comment]
MrBricodage,

I made a test. Reproduction step as below.
1. Create a test suite "A";
2. Create two test suite "A1", "A2" under the test suite "A";
3. Create test cases under test suite "A1" and "A2";
4. Export test suite "A";
5. Import this "A" test cases into ImportExcelMacro tool;
Actual Result:
It will import the first test suite "A1" test cases successfully, and then prompt an error, "Running Error '9' index bound";
So I think this issue it not related to my 800+ items data.
My company can't send outer email, so I can't send these XML file to you, and I can't copy them to my personal memory device.
But I can send my test XML file in my home computer, if you can tell me your Email.

Thanks advance.
Kelly

**Comment by takase1024** [comment]
I also the same problem had occurred.
Now working fine.
Change the following

```importXML.bas
'--------------
'TestSuite Management
'--------------
'Case "<testsuite name" To "<testsuite namf" 'linked to Case "<details"
Case "<testsuite id" To "<testsuite if" 'linked to Case "<details"

**Comment by kellykbl** [comment]
Thanks takase1024
I also found this defect. 
Testlink 1.9.13 add "ID" for testsuite in exported xml file.

**Comment by MrBricodage** [comment]
the next version will integrate this modification : 
'--------------
'TestSuite Management
'--------------
'Case "<testsuite name" To "<testsuite namf" 'linked to Case "<details", compatible with TL version prior to 1.9.13
TShierarchy = ...

'Case "<testsuite id" To "<testsuite ie" 'linked to Case "<details", compatible with TL version 1.9.13 and later
TShierarchy = ...

thank you for your feedback.

**Comment by MrBricodage** [comment]
modification provided in 20150831 release
