### ISSUE TITLE
runtime error in import.

### ISSUE THREAD

**Issue by takase1024** [MrBricodage/TestLink--ImportExcelMacro#6]
Hello 
I will try to use ImportExcelMacro tools with  on testlink 1.9.13.

I can't import XML to ExcelMacro template.

Please advise me.

Procedure is as follows:

1. Open 02-ImportTestCasesIntoTestLink.xls
1. enable edit.
1. enable contents
1. Click Import TestCases From TestLink.
1. Confirmation -> OK
1. Select file for-issue.xml
(File is https://github.com/takase1024/TestLink--ImportExcelMacroIssue/blob/master/runtime-error/for-issue.xml)

screenshot is in https://github.com/takase1024/TestLink--ImportExcelMacroIssue/tree/master/runtime-error

**Comment by takase1024** [comment]
Now working fine.
Change the following

```importXML.bas
'--------------
'TestSuite Management
'--------------
'Case "<testsuite name" To "<testsuite namf" 'linked to Case "<details"
Case "<testsuite id" To "<testsuite if" 'linked to Case "<details"

**Comment by takase1024** [comment]
Check was loose.
It is not output some of the items such as Step.

**Comment by MrBricodage** [comment]
see bug #5
