### ISSUE TITLE
The characters were garbled

### ISSUE THREAD

**Issue by takase1024** [MrBricodage/TestLink--ImportExcelMacro#7]
Hello 
The characters were garbled in japanese environment.
It is using a modification to the appropriate character as an interim response.

Is there a good measure?

garbled Function is 
- ReplaceFrenchChar
- ReplaceHTMLChar

Screen shot is in the following.
https://github.com/takase1024/TestLink--ImportExcelMacroIssue/tree/master/Damaged-VBA

**Comment by MrBricodage** [comment]
Hello,

yes, some characters have to be replaced (encoding seems to be the problem). 

A function is provided for french chars.

You can add char replacements in ReplaceFrenchChar() or (better) create a new function ReplaceJapaneseChar() and replace call to ReplaceFrenchChar by ReplaceJapaneseChar() in the code.

The new function could be intregrated in trunk, and you won't have to modify each new version of the excel files.

Regards
